### ISSUE TITLE
კარელის სამუშაო გარემოს გამართვის ინსტრუქცია

### ISSUE THREAD

**Issue by iarigby** [iarigby/digital-technologies#2]
ახლა ცალკე იწერენ ჯავას (სტენფორდის სერვერიდან, ძალიან ნელა) და მერე JSKarel-ს, და ორივე ლინკზე არის ვინდოუსის და მაკის ვერსიები. უფრო მარტივი იქნება თუ 

- გამზადებული იქნება ცალკე ვინდოუსისთვის, ცალკე მაკისთვის
- google drive-ზე იქნება ორივე ოპერატიული სისტემის ფოლდერი
- ეს ყველაფერი იქნება დალინკული გვერდზე, ტექსტურ ინსტრუქციასთან ერთად (და troubleshoot რაც გამოჩნდება შეიძლება სქრინებიც) 

წინა ინსტრუქცია არის აქ:

https://classroom.google.com/u/2/c/NTM3MTA4ODI1ODJa/m/NjEyMDA1MzYzMDFa/details'

ახალი ინსტრუქცია იქნება content/resources/karel_de.md -ში

**Comment by khokho** [comment]
32 ბიტიანის ლინკის ჩაგდება დამავიწყდა და გავასწორებ მერე.

**Comment by iarigby** [comment]
მშვენიერია
