### ISSUE TITLE
კომენტარების დამატება საიტზე

### ISSUE THREAD

**Issue by iarigby** [iarigby/digital-technologies#3]
## მოტივაცია
რამდენიმე მიზეზი, რის გამოც google classroom-ზე მოუხერხებელია დისკუსია
- არ აქვს upvote/downvote სისტემა და შესაბამისად რელევანტურობის მიხედვით კომენტარების დამატება
- არ აქვს nested replies და შეუძლებელია ერთ პოსტზე რამდენიმე სხვადასხვა მიმართულების საუბარი
- ყველა საკითხზე პოსტები/კომენტარები არის გაერთიანებული ერთ სივრცეში და ძებნას აზრი არ აქვს (ctrl+F უწერიათ რეკომენდაცია :) )
- არ არის ტექსტის ფორმატირება, სურათების დამატების საშუალება

ამ საიტზე მიზანი არის, რომ ნებისმიერი კითხვა, რომელიც სტუდენტს ექნება, რომელიმე გვერდის კომენტარებს შეეასაბამებოდეს და იქ დაწეროს. სხვა სტუდენტი როდესაც იმ გვერდს წაიკითხავს და იგივე კითხვა გაუჩნდება, მარტივად ნახავს. შეიძლება კომენტარის პასუხი გვერდის ტექსტშიც დაემატოს, მაგრამ თუ ვინმემ მანამდე ნახა, უბრალოდ ახალ კომენტარს წაიკითხავს ბოლო ცვლილებების გასაგებად

## ტექნიკური დეტალები
Github pages იყენებს jekyll-ს სტატიკური საიტების შესაქმნელად. სტატიკურ საიტებზე კომენტარების დასამატებლად გამოიყენება ხოლმე რამე ვებ სერვერი და ჯეკილზე _includes თემფლეითში ემატება სკრიტპ თეგი, რომელიც უკავშირდება სერვერს და რომელიმე div-ში გამართავს კომენტარებს. დახურული ასეთი სერვისი არის [disqus](https://disqus.com/).

ღია ვარიანტებიდან ავარჩიე remark42 ([დემო](https://remark42.com/demo/)). ერთადერთი იყო, რომელიც ყველა ამ პირობას აკმაყოფილებდა ([ყველა ფუნქცია](https://remark42.com/))
- სერვერზე მარტივად გასამართია
- google sign-on მარტივად ემატება და უნივერსიტეტის ექაუნთებით შეძლებენ დაკომენტარებას.
- აქვს მინიმალური memory footprint (დაწერილია go-ში)
-  მიგრაციაც მარტივია (დოკერ კონტეინერშივე არის მინიმალისტური მონაცემთა ბაზა და ცალკე მიგრირება არაა საჭირო)

მიუხედავად იმისა, რომ მარტივია მიგრაცია, მაინც ვფიქრობ რომ მერაბს ვთხოვო ძალიან პატარა dedicated სერვერის გამოყოფა, რომ სემესტრების განმავლობაში შენარჩუნდეს (და შეიძლება სხვა საგნებში დაემატოს ვინც ამ სტრუქტურას გამოიყენებენ).

- რემარკის დოკუმენტაცია არის მთლიანად პროექტის README-ში https://github.com/umputun/remark42 . 
- github pages-ზე დაემატება იგივე პრინციპით, რომლითაც მაგალითად disqus. აქ არის [ინსტრუქცია](https://stackoverflow.com/a/29582010) (_includes დირექტორია შექმენი და იქ ჩასვი თემფლეითი)
- ჯერ უბრალოდ წაიკითხე რა არის და როგორ მუშაობს და ხვალ საღამოს მოგცემ სერვერის მონაცემებს

**Comment by khokho** [comment]
ლოკალურად ავამუშავე ყველაფერი. ყველა გვერდზე რო არ მოგვიწიოს include ის წერა ლეიაუთის გაკეთება შეიძლება. 
layout: commetable მაქვს და ახლა და _config ში დეფაულტად გავწერე ეგ. 
ლოგინი არ დამიმატებია ჯერ მაგრამ ანონიმური ლოგინით მუშაობს მშენივრად ჯერჯერობით.(გათიშვა შეიძლება ამის)

**Comment by khokho** [comment]
სერვერს თუ მომცემ შემიძლია გავმართო.

**Comment by iarigby** [comment]
ძალიან მაგარია. კი ახლა ვაორგანიზებ მაგას. უნივერსიტეტის სერვერი არ ვიცი როდის იქნება მზად, მონაცემები ნორმალურია მაგრამ უბუნტუა მარტო და edu.ge-ით digitaloceanზე თუ მომცა უფასო კრედიტი ავიღებ, ან hetzner-ზე გავაკეთებ და მოგცემ დეტალებს

**Comment by khokho** [comment]
close-ზე დამეჭირა 😅
სერვერზე მერაბს თუ არ ველოდებით მაშინ მეც ვიჩალიჩებ edu.ge თი.

**Comment by iarigby** [comment]
მივწერე და ძალიან მალე მიპასუხა დეტალები მკითხა და მალე გამოგვიგზავნიან სავარაუდოდ. შენთვის შეინახე გამოგადგება ძაან ბევრი one click app აქვთ მაგათ.

**Comment by khokho** [comment]
ეს მუშაობს მოკლედ უბრალოდ დარჩა რამდენიმე პრობლემა:
1) ის სერვერი ძალიან ნელია მგონი 
2) https-ს ვარკვევ რემარკის მხარეს იმიტორო ისე ბრაუზერები ბლოკავენ
3) google ლოგინისთვის საჭირო არის დომეინი ამ წუთას 217.147.224.204.xip.io-ს ვიყენებ რომელიც აიპის დომეინად ასაღებს.

**Comment by khokho** [comment]
მაგიურად სსლ-ის გასწორებამ ყველაფერი 1000-ჯერ დააჩქარა. 
.xip.io -ს გამოყენება მგონი პრობლემა არაა, უბრალოდ login ისას xip.io -ს წერს გუგლის ექაუნთს რო ირჩევ. 
შეამოწმე აბა.

**Comment by khokho** [comment]
ექაუნთს რო დააჭეც ცალკე ისტორის ფუნქცია ქონია 😮

**Comment by iarigby** [comment]
ძალიან მაგარია :o ანონიმური გამოურთე უბრალოდ.

> უბრალოდ login ისას xip.io -ს წერს გუგლის ექაუნთს რო ირჩევ

0 ადამიანი შეხედავს :D შუის მერე არის ლექცია როცა ვეუბნები რომ ინტერნეტში
არავის ენდონ და ყველაფერი შეამოწმონ

**Comment by iarigby** [comment]
თან როგორი ნავაროჩენი საიდბარი გამოდის :დ

**Comment by khokho** [comment]
გამოვრთე ანონიმურიც.

**Comment by khokho** [comment]
ადმინის უფლებები მივეცი ჩვენ ორ ექაუნთს. აპინვა, წაშლა და ვინმეს დაბლოკვა :დ შეგვიძლია.

**Comment by iarigby** [comment]
კი ახლა შევედი გვერდზე და მაგითაც აღვფრთოვანდი :D ერთი-ორჯერ კი მოუნდა დიდი ხანი სერვერთან დაკავშირებას, დავაკვირდები და თუ დისკომფორტი შეგვიქმნა მერე ავიღებ ჰეცნერზე რამეს. ssh კავშირისასაც იყო delay?

**Comment by khokho** [comment]
რამდენჯერმე დავარსტარტე დოკერი და ახლა დიდი ხანი შეიძლება ამიტო უნდოდა, თორე ისე არაა მგონი ნელი. 

ssh ცოოტა ნელი იყო მარა ძაანაც არა.

**Comment by khokho** [comment]
პირველ გახსანზე არის ხოლმე ნელი კიდე remark.js და remark.css ის წამოღება არის ნელი. მარა მერე იქეშება და არაა პრობლემა.

**Comment by khokho** [comment]
საბოლოოდ დავასკვენი რომ ყველაფერი ჩქარია ssl ჰენდშეიკის ის გარდა :დ გასწორება ვცადე სხვადასხვა გზით მარა არ ეშველება მგონი :დ. და არც სხვა სერვერი არ შეცვლის დიდად ჩემი აზრით.

**Comment by iarigby** [comment]
ჰო tls მიჩვენებდა მეც ყველაზე დიდ ხანს. კაი იყოს მოკლედ ასე. სერვერთან
ssh-ს რაც შეეხება, იმედნად ხშირად არ იქნება საჭირო დაკავშირება და ძალიან
ნელი თუ არაა ეგეც იყოს.

**Comment by iarigby** [comment]
@khokho შეგიძლია ერთი .md გვერდი გააკეთო utilities-ში, სადაც სერვერზე გასაშვები ბრძანებები (და რამე დამატებითი კონფიგურაცია) იქნება?
